name: XML Atlas CI build
run-name: XML Atlas CI build by ${{ github.actor }}
on: [push]

env:
  BUILD_TYPE: Release

jobs:
  XML-Atlas-on-Ubuntu-20-04:
    name: Building XML-Atlas on Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: Install Qt5
        run: |-
          sudo apt-get install -yq qt5-default
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --target all --parallel

  
  XML-Atlas-on-Ubuntu-22-04:
    name: Building XML-Atlas on Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - name: Install Qt6
        run: |-
          sudo apt-get install -yq qt6-base-dev libglx-dev libgl1-mesa-dev
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --target all --parallel


  XML-Atlas-qt5-on-Windows:
    name: Building XML-Atlas-Qt5 on Windows
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --parallel


  XML-Atlas-qt6-on-Windows:
    name: Building XML-Atlas-Qt6 on Windows
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.2'
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --parallel